baseURL = "https://zyyujkkj.github.io/my-hugo-site/"
languageCode = 'zh-cn'
title = 'Zyu的学习记录'
theme = 'PaperMod'
relativeURLs = true
canonifyURLs = true

[params]
  author = "zyu"
  defaultTheme = "auto"
  ShowReadingTime = true
  ShowPostNavLinks = true
  ShowRecentPosts = true

[menu]
  [[menu.main]]
    name = "主页"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "归档"
    url = "/archives/"
    weight = 2

  [[menu.main]]
    name = "标签"
    url = "/tags/"
    weight = 3

